### ISSUE TITLE
MAC OSX 10.11.6 error

### ISSUE THREAD

**Issue by hktalent** [kti/python-netfilterqueue#14]
sudo python ~/pip2.py  install  --ignore-installed --trusted-host pypi.douban.com  -i http://pypi.douban.com/simple NetfilterQueue
Collecting NetfilterQueue
  Downloading http://pypi.doubanio.com/packages/7b/c3/204d47c1c47a7fd6ac1e4e341bdc6021f8142e6c7b6e488436592a6d2488/NetfilterQueue-0.7.tar.gz (55kB)
    100% |████████████████████████████████| 61kB 898kB/s 
Installing collected packages: NetfilterQueue
  Running setup.py install for NetfilterQueue ... error
    Complete output from command /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-qrP4zk/NetfilterQueue/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WDyKSL-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    cythoning netfilterqueue.pyx to netfilterqueue.c
    building 'netfilterqueue' extension
    creating build
    creating build/temp.macosx-10.11-x86_64-2.7
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c netfilterqueue.c -o build/temp.macosx-10.11-x86_64-2.7/netfilterqueue.o
    netfilterqueue.c:276:10: fatal error: 'libnfnetlink/linux_nfnetlink.h' file not found
    #include "libnfnetlink/linux_nfnetlink.h"
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-qrP4zk/NetfilterQueue/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WDyKSL-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-qrP4zk/NetfilterQueue/

**Comment by mattfox** [comment]
[libnetfilterqueue](http://www.netfilter.org/projects/libnetfilter_queue/) is a Linux-only feature, so you won't be able to install python-netfilterqueue on Mac OS.

**Comment by hktalent** [comment]
but ..........
pip install  python-netfilterqueue
brew install python-netfilterqueue
port  install python-netfilterqueue

not find
