### ISSUE TITLE
hi, how to install in mac os...

### ISSUE THREAD

**Issue by binlaniua** [kti/python-netfilterqueue#2]
'''
netfilterqueue.c:239:10: fatal error: 'libnfnetlink/linux_nfnetlink.h' file not found
    #include "libnfnetlink/linux_nfnetlink.h"
'''

**Comment by wimkerkhoff** [comment]
We haven't tried this on Mac OSX at all. NetFilter is Linux specific and I don't know of any Mac OSX alternative offhand.

**Comment by calebcauthon** [comment]
@binlaniua did you ever solve this?

**Comment by mattfox** [comment]
Sorry, python-netfilterqueue will not work on Mac because nfqueue is Linux-only: http://www.netfilter.org/projects/libnetfilter_queue/index.html

**Comment by greycr0w** [comment]
Any alternative option would greatly appreciated.
