### ISSUE TITLE
Crash in Packet_set_nfq_data with version 0.8

### ISSUE THREAD

**Issue by dverbeir** [kti/python-netfilterqueue#24]
Version 0.7 works fine but 0.8 gives a segfault in Packet_set_nfq_data. It usually works for a few packets before causing the segfault. I did not observe anything special about the packet at which it crashes.

This was observed on Debian Jessie.

**Comment by mattfox** [comment]
#25 duplicated this report, but more activity happened on that issue so I'm closing this one. Feel free to re-open if you have reason to believe that was a actually different issue. Thanks for the report.
