### ISSUE TITLE
Crash in iptables OUTPUT chain 

### ISSUE THREAD

**Issue by genesisgardian** [kti/python-netfilterqueue#25]
Hi,
I'm writing a simple code to capture the packet, and print the packet, just as the example code which you give to us. It works fine as the INPUT chain of iptables, but when I change to capture the output packet with OUTPUT chain of iptables, it crash and show the 'segmentation fault'.

I'm working on Ubuntu 16.04

**Comment by danyunfu** [comment]
I ran into a similar issue with version 0.8 and 0.6 on Ubuntu 14.04; PREROUTE works fine, POSTROUTE crashes. Seems ok so far on 0.7

**Comment by Tey** [comment]
Problem is at [line 65 of netfilterqueue.pyx](https://github.com/kti/python-netfilterqueue/blob/27cd73f7ca0eea46973b9218d0f6ae5fc9e0face/netfilterqueue.pyx#L65):
```python
        self.hw_addr = self._hw.hw_addr
```

When sending packets, `self._hw` is `NULL` so the copy crashes. I have no idea how to fix that in the PYX file (what should be the value of `self.hw_addr` when `self._hw` is `NULL`?), but as a workaround, you can just comment the [following lines in `netfilterqueue.c`](https://github.com/kti/python-netfilterqueue/blob/27cd73f7ca0eea46973b9218d0f6ae5fc9e0face/netfilterqueue.c#L2160) and compile/install the module again:
```C
  __pyx_t_2 = __pyx_v_self->_hw->hw_addr;
  memcpy(&(__pyx_v_self->hw_addr[0]), __pyx_t_2, sizeof(__pyx_v_self->hw_addr[0]) * (8 - 0));
```

**Comment by ojalexander** [comment]
I ran into the same issue using OUTPUT. Thanks for the workaround.

**Comment by mattfox** [comment]
Thanks for the details. I'll see if I can duplicate and fix within a few days.

**Comment by mattfox** [comment]
The fix leaves calling and parsing of nfq_get_packet_hw data until the `get_hw()` call, and just returns None if nfq_get_packet_hw returns NULL. I believe `hw_addr` was private on `Packet`, so this should be compatible with 0.8.

I've uploaded 0.8.1 to Pypi but reviews and improvements are welcome. Thanks for reporting this, all.

**Comment by Tey** [comment]
Thanks @mattfox I experience no more crash with 0.8.1.
