### ISSUE TITLE
packet.set_payload() implementation

### ISSUE THREAD

**Issue by LFindanno** [kti/python-netfilterqueue#3]
Hallo, many tanks for your work. I would ask you to implement the "packet.set_payload()" function. It will be very usefull for all python programmer community.
Best regards.
yousdo

**Comment by exploide** [comment]
It seems this is resolved since #1 has been merged. The only thing left is that README.rst still states that `packet.set_payload()` is omitted but it should work.

**Comment by mattfox** [comment]
README is updated now. Since https://github.com/kti/python-netfilterqueue/issues/11 refers to the pypi package, I'll close this issue. Thanks.

**Comment by dvstter** [comment]
I am using 0.8version, but the set_payload seems didn't work, can anybody help me? The link below is my question's details. http://stackoverflow.com/questions/43319070/netfilterqueue-set-payload-not-work
