### ISSUE TITLE
Capture traffic from a specific interface

### ISSUE THREAD

**Issue by rbshadow** [kti/python-netfilterqueue#39]
Is there any way to capture traffic from a specific interface with NetfilterQueue?

**Comment by mattfox** [comment]
Yes, netfilter_queue will give you the packets matched by your iptables rule. So where the readme says:

    iptables -I <table or chain> <match specification> -j NFQUEUE --queue-num <queue number>

then `<match specification>` is something like:

    -i eth0

For example:

    iptables -I INPUT -i eth0 -j NFQUEUE --queue-num 0

**Comment by rbshadow** [comment]
Thank you very much.
