### ISSUE TITLE
Is this package still maintained? 

### ISSUE THREAD

**Issue by r0bc94** [kti/python-netfilterqueue#40]
Hey, 

I wonder if this package is still maintained, since the last update is from the *31.01.2017* but the status on pypi is still at *5 - Production/Stable*. 

 I would appreciate your answer.

**Comment by mattfox** [comment]
Sure, if you'd like to submit a pull request I'd take a look at it.

**Comment by adisbladis** [comment]
@mattfox Could you take a look at this one https://github.com/kti/python-netfilterqueue/pull/32 ?
It's been open for over a year and it's pretty trivial.

**Comment by mattfox** [comment]
Yeah, my apologies. I will comment on the PR.
