### ISSUE TITLE
COPY* constants are WRONG!

### ISSUE THREAD

**Issue by socketpair** [kti/python-netfilterqueue#6]
```
COPY_NONE = 1
COPY_META = 2
COPY_PACKET = 3
```
it should be
```
COPY_NONE = 0
COPY_META = 1
COPY_PACKET = 2
```

Tests? no, did not hear...

**Comment by K-Yo** [comment]
src : https://git.netfilter.org/libnetfilter_queue/tree/include/libnetfilter_queue/linux_nfnetlink_queue.h#n82

**Comment by socketpair** [comment]
C enums starts with zer o(!) http://stackoverflow.com/questions/6434105/are-default-enum-values-in-c-the-same-for-all-compilers
